export const USER_ME = 'USER_ME';
export const USER_ACTIVATION = 'USER_ACTIVATION';

export const MY_CALENDARS = 'MY_CALENDARS';
export const PARTICIPATING_CALENDARS = 'PARTICIPATING_CALENDARS';

export const CALENDAR_INVITATIONS = 'CALENDAR_INVITATIONS';
